server:
  port: 8080
  servlet:
    context-path: /
  ip: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
