server:
    port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    pool:
      max-active: 200
      max-wait: 300
      max-idle: 50
      min-idle: 10
    timeout: 30000
    url: redis://user:bizidealyf123@10.1.3.105:6379/1

mybatis:
  #mapper.xml存放位置
  mapper-locations: classpath*:mapper/*Mapper.xml
  #映射实体类存放位置
  type-aliases-package: com.sy.study.springboot.demo.bean